name: pr
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        api-version: [31, 40, 47] # https://eway.io/api-v3/?ruby#api-versioning
        ruby-tag: [2.3.7, 2.7.1, 3.0.6]

    env:
      EWAY_API_VERSION: ${{ matrix.api-version }}
      RUBY_TAG: ${{ matrix.ruby-tag }}

    steps:
      - run: sudo apt-get update && sudo apt install -y --no-install-recommends libgmp3-dev
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-tag }}
          bundler-cache: true
      - run: bundle exec rake
